export default [{
        title:"基础信息",
        items:[{
                name:"分类管理",
                path:"/category"
            },{
                name:"颜色管理",
                path:"/color"
            },{
                name:"规格管理",
                path:"/spec"
            },
        ]
    },{
        title:"库存管理",
        items:[{
                name:"商品基础数据",
                path:"/stock"
            }
        ]
    },{
        title:"商品管理",
        items:[{
                name:"商品标签",
                path:"/tag"
            },{
                name:"商品图片",
                path:"/image"
            },{
                name:"商品详情",
                path:"/detail"
            },{
                name:"上下货架",
                path:"/sell"
            }
        ]
    },{
        title:"方案管理",
        items:[
            {
                name:"UI管理",
                path:"/diy"
            },
            {
                name:"方案列表",
                path:"/scene"
            },
        ]
    },
    {
        title:"促销管理",
        items:[{
            name:"促销列表",
            path:"/promotionlist"
            },{
                name:"限时折扣",
                path:"/discount"
            },{
                name:"多人拼团",
                path:"/promGroup"
            },{
                name:"砍价活动",
                path:"/bargain"
            },{
                name:"sku组合",
                path:"/skugroup"
            },{
                name:"优惠券",
                path:"/coupon"
            },
        ]
    },
    {
        title:"订单管理",
        items:[{
                name:"订单列表",
                path:"/order"
            },
            {
                name:"订单发货",
                path:"/ordersend"
            }
        ]
    },
    {
        title:"用户管理",
        items:[{
            name:"导购管理",
            path:"/guider"
            }
        ]
    },
    {
        title:"场景管理",
        items:[{
            name:"VR全景管理",
            path:"/vrscene"
            }
        ]
    },
    {
        title:"APP管理",
        items:[{
                name:"App列表",
                path:"/app"
            }
        ]
    },
    {
        title:"2019大屏展示",
        items:[{
                name:"全景管理",
                path:"/exhibition"
        }]
    }
];