export default [{
        title:"概况",
        path:"/nosupport"
    },{
        title:"报名",
        path:"/nosupport"
    },{
        title:"学员",
        path:"/nosupport"
    },{
        title:"线下课",
        path:"/offlinecourse"
    },{
        title:"线上课",
        path:"/nosupport"
    },{
        title:"动态",
        path:"/nosupport"
    },{
        title:"财务",
        path:"/nosupport"
    },{
        title:"设置",
        path:"/nosupport"
    }
];