export default [{
        title:"基础信息",
        items:[{
                name:"分类管理",
                path:"/category"
            },{
                name:"颜色管理",
                path:"/color"
            },{
                name:"规格管理",
                path:"/spec"
            },
        ]
    },{
        title:"库存管理",
        items:[{
                name:"商品基础数据",
                path:"/stock"
            }
        ]
    }
];